apiVersion: v1
kind: Pod
metadata:
  name: efs-temp
spec:
  containers:
  - name: efs-temp
    image: debian:stable-slim
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "900Mi"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - mountPath: /temp/efs
        name: temp-efs
  volumes:
    - name: temp-efs
      nfs:
        path: /
        server: ${EFS_ID}.efs.${REGION}.amazonaws.com
